workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - SmartCV Keystore
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build AAB
        script: flutter build appbundle --release --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.aab